version: "3.9"

services:
  etcd:
    image: bitnami/etcd:3.5.1-debian-10-r4
    container_name: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - etcd_data:/bitnami/etcd
    restart: always
  server:
    image: jirituryna/ctcgrpc:main-b0e4568-220506125928
    container_name: ctcgrpc
    command: [ "server","--etcd=etcd:2379" ]
    ports:
      - "8080:8080"
    depends_on:
      - etcd
volumes:
  etcd_data:
    driver: local



